[package]
name = "ps_rust_main"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

[workspace]
members = ["templates"]

[dependencies]
# rand = "0.8.5"

[[bin]]
name = "main"
path = "main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.htm:
